name: Go Checks
on: 
  push:
    branches:
      main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Tidy
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.55'
          skip-pkg-cache: true
      - name : Test
        run: go test -v ./...
      - name: Build
        run: go build -v ./...
