name: Go Checks
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
      - run: go mod tidy
      - uses: golangci/golangci-lint-action@v4
        with:
          version: 'v1.56'
          skip-pkg-cache: true
      - run: go build -v ./...
      - run: go test -v ./...
